name: Build for static site

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - name: Run a multi-line script
        uses: actions/setup-node@v4
        with: 
          node-version: '18'
      - run: npm ci
      - run: npm run build

      - name: Init new repo in build folder and commit files
        run: |
          cd build
          git init
          git add -A
          git config --global --add safe.directory /github/workspace
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Action"
          git commit -m 'Build'

      - name: Force push to build branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: build
          force: true
          directory: ./build
