name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Adjust this if you use a different default branch
  pull_request:
    branches:
      - main  # Adjust this if you want the action to trigger on PRs to the default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '23'  # Adjust to your Node.js version

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and Push Docker image for amd64 and arm64
      run: |
        docker buildx build . \
          --platform linux/amd64,linux/arm64 \
          -t ${{ secrets.DOCKER_HUB_USERNAME }}/melo-minimalist:latest \
          --push
